# Site settings
title: Duodecimo Introdução à Aprendizagem de Máquina
description: "Materiais e notas do curso livre de introdução à aprendizagem automática na Universidade Severino Sombra, Vassouras, RJ."
baseurl: ""
url: "duodecimo.github.io/duodecimoMachineLearning"
github_username:  duodecimo

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
